### ISSUE TITLE
有点小Bug

### ISSUE THREAD

**Issue by Alfred-Cyan-Allen** [chquanquan/AreaPickerView_swift#1]
哥们儿，谢谢啊，节约不少时间。
不过有个小bug，选择第二列最后一项的时候第三列不会更新。错误原因应该是reloadAreaComponent方法中的判断guard row < cities.count - 1 else { return }，改为<=就好了。不过没有具体看代码，不知道会不会导致别的问题。

**Comment by chquanquan** [comment]
已经按@yanhaovgo提的意见,修复了BUG...thanks
