### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by bianzhifeng** [chquanquan/AreaPickerView_swift#2]
hi.
 我使用了你的pickerView , 但是当我 创建的时候
AreaPickerView.picker(for: self, textField: nickNameTextField) 报了错误 ,  错误名为Generic parameter 'controller' could not be inferred ,  我为什么编译你的项目没有这个错误 而且我确定我声明了controller 的类型为UIViewController , 我不明白为什么会在我的项目中报这种错误.

**Comment by chquanquan** [comment]
你有遵守 AreaPickerDelegate 协议没?   UIViewController需要遵守这个协议才行.
 不好意思,现在才看到...其实你可以QQ我的,号码在 readme..
